### ISSUE TITLE
Implement StakingFactory

### ISSUE THREAD

**Issue by izqui** [aragon/staking#9]
Given that one Staking instance only manages one token, we should have factory to create new instances and find instances for deployed tokens.

I propose we use a model similar to Uniswap's: `Factory#instanceFor(ERC20 token) public returns (Staking)` if the staking instance doesn't exist for the token address, it will use `CREATE2` for deploying a thin, non-upgradeable DelegateProxy to the Staking implementation, and return the address of the staking instance. If it already exists, it will just return the address.

```
contract ThinProxy is DelegateProxy {
    constructor(address _implementation) {
        assembly { sstore(P, _implementation) }
    }

    function implementation() public view returns (address implementation) {
        assembly { implementation := sload(P) }
    }
}
```

**Comment by facuspagnuolo** [comment]
Update: we decided not to use `create2` for this factory, we will handle staking instances with a mapping and regular deployments
